### ISSUE TITLE
Tracking Hours by Year / Period of Time

### ISSUE THREAD

**Issue by Jimmy-Zeng** [oc-hacker/Voluntu-Issues#2]
Could there be filter to check, for example, only my hours during the 2016-2017 school year, or only between last August to October? Since right now we can only see our TOTAL hours, including those from last year, but when we need to sign our hours onto a physical sheet for school records, we cannot see which events we have already gotten signed for and which ones we still have left. Especially when we get our records tracking sheets signed, the adult prefers to sign one large, cumulative entry over say, a month or 3, rather than for each individual entry.

**Comment by sguo35** [comment]
Filtering by PVSA year will be implemented soon.

**Comment by sguo35** [comment]
Filtering by PVSA year has been implemented.
