### ISSUE TITLE
Wrong "View Hours" Headers

### ISSUE THREAD

**Issue by KimberlyShi** [oc-hacker/Voluntu-Issues#3]
<img width="512" alt="2017-05-01_1024" src="https://cloud.githubusercontent.com/assets/28974545/26483580/a5301174-41a2-11e7-8d50-4994af47858e.png">

Under the "Hours" header, it displays the organization. Under "Organization," it displays the activity description.

**Comment by sguo35** [comment]
Fixed by [Fix hour display bug](https://github.com/OC-Hackers/Volunteer-App-Client/commit/4fe21bd2f872d57a2c1382159a8b59d753d3eae3) and [PR#43](https://github.com/OC-Hackers/Volunteer-App-Client/pull/43)
