### ISSUE TITLE
No checkboxes for approve hours

### ISSUE THREAD

**Issue by amy-zhong** [oc-hacker/Voluntu-Issues#6]
Hello,

I cannot approve hours using the General Supervisor account because the checkboxes do not appear no matter how much I minimize the screen. Could you make the descriptions loop back around instead of just running off the screen?
![screen shot 2017-08-31 at 6 09 32 pm](https://user-images.githubusercontent.com/31525782/29951445-9266ab9e-8e77-11e7-8671-27e2c066e859.png)
Thanks,
Amy Zhong

**Comment by syy1125** [comment]
A simple styling issue. I made a fix, but it's not deployed yet.

**Comment by jason-s-yu** [comment]
Issue should be fixed.
